---
title: "Netflix im Wandel der Zeit"
author: "Márk Reichmann, Simon Keil, Daniel Henke"
date: \today
header-includes:
   - \usepackage[ngerman]{babel}
output: 
  beamer_presentation:
    theme: Singapore
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
	echo = FALSE, message = FALSE)

library("tidyverse")
raw_data <- read_csv("../Data/netflix-rotten-tomatoes-metacritic-imdb.csv")

data <- raw_data %>%
  rename(country = 'Country Availability') %>%
  # reformat release date to only the year
  mutate(year = as.integer(substr(`Release Date`, 8, 12))) %>% 
  # exclude years with close to no entries
  filter(year > 1965 & year < 2020) %>% 
  select(Title, year, Genre, country) %>%
  drop_na()

# unique content + Genre
content_genre <- data %>%
  select(Genre, year, Title) %>% 
  separate_rows(Genre, sep = ", ") %>%
  distinct(.keep_all = TRUE)

# unique content + country
content_country <- data %>%
  select(year, Title, country) %>% 
  separate_rows(country, sep = ",") %>%
  distinct(.keep_all = TRUE)

# dataset with list of genres and countries separated into individual rows
data_expanded <- full_join(content_genre, content_country, by = c("year", "Title")) %>%
  ungroup()

# dataset with list of genres separated into individual rows
data_genre <- data_expanded %>%
  group_by(Genre, year, Title) %>%
  summarise(country = paste(country, collapse = ", ")) %>%
  ungroup()

# dataset with list of countries separated into individual rows
data_country <- data_expanded %>%
  group_by(country, year, Title) %>%
  summarise(Genre = paste(Genre, collapse = ", ")) %>%
  ungroup()

# dataset to work with throughout the analysis
data_basic <- data_genre %>%
  group_by(country, year, Title) %>%
  summarise(Genre = paste(Genre, collapse = ", ")) %>%
  ungroup()
```


# Tibble modifizieren (1)

unser Datensatz (die interessanten Variablen):
\tiny
```{r}
data
```
\normalsize

`year` und `Title` sind nur zusammen eindeutig
\tiny
```{r}
raw_data %>%
  mutate(year = as.integer(substr(`Release Date`, 8, 12))) %>%
  select(Title, year, `Series or Movie`) %>%
  filter(Title == "Cloudy with a Chance of Meatballs")
```
\normalsize

# Tibble modifizieren (2)

leider gibt es Duplikate:
\tiny
```{r echo=TRUE}
data %>%
  count(Title, year)%>%
  filter(n>1)
```
\normalsize

# Tibble modifizieren (3)

das sind diejenigen Filme, die mehrmals auf Netflix releast wurden
\tiny
```{r}
data%>%
  filter(Title == "A Perfect Day")
```
\normalsize


Lösung: 
\tiny
```{r}
countries = data %>%
  filter(Title == "A Perfect Day") %>%
  select(Title, year, country)%>% 
  separate_rows(country, sep = ",")%>%
  distinct(.keep_all = TRUE)

genres = data %>%
  filter(Title == "A Perfect Day") %>%
  select(Title, year, Genre)%>% 
  separate_rows(Genre, sep = ", ")%>%
  distinct(.keep_all = TRUE)

data_tidy <- full_join(countries, genres, by = c("year", "Title"))

data_tidy %>%
  group_by(Title, year, country) %>%
  summarise(Genre = paste(Genre, collapse = ", ")) %>%
  group_by(Title, year, Genre) %>%
  summarise(country = paste(country, collapse = ", ")) %>%
  ungroup()
```

\normalsize
#

```{r}
data_basic %>% 
  count(year) %>% 
  ggplot(aes(x = year, y = n)) +
  geom_point() +
  scale_y_log10() +
  labs(x = "Veröffentlichungsjahr",
    y = "Anzahl der Inhalte") +
  theme_light(20)
```

#

```{r}
data_country %>%
  count(country)%>%
  select(n, country)%>%
  ggplot(aes(x = n, y = reorder(country, n)))+
  geom_point()+
  labs(title = "Anzahl verfügbarer Inhalte in den Ländern",
       x = "Anzahl der Inhalte", 
       y = "Land") +
  theme_light(18)
```

#

```{r}
data_country %>% 
  count(Title, year) %>%
  group_by(year) %>% 
  summarise(number = mean(n)) %>%
  ggplot(aes(x = year, y = number)) +
  geom_point() +
  labs(title = "Internationalität im zeitlichen Verlauf",
       y = "Durchschnittliche Zahl der Länder pro Inhalt",
       x = "Veröffentlichungsjahr") +
  geom_smooth() +
  theme_light(20)
```

#

```{r}
data_genre %>%
  count(Genre) %>% 
  arrange(n) %>%
  ggplot(aes(x = factor(Genre, levels = Genre), y = n)) +
  geom_bar(stat = 'identity') +
  labs(title = "Ranking der Genres",
    x = "Genre",
    y = "Anzahl der Inhalte") +
  coord_flip() +
  theme_light(20)
```

#

```{r}
year_per_genre <- data_genre %>%
  count(year, Genre)
year_genre_total <- data_genre %>% count(year)
left_join(year_per_genre, year_genre_total, by = "year") %>% 
  mutate(prop = n.x/n.y) %>% 
  ggplot(aes(x = year, y = prop, color = Genre)) +
  geom_point(size = 1) +
  labs(title = "Anteil der verfügbaren Genres nach Veröffentlichungsjahr",
    x = "Veröffentlichungsjahr",
    y = "Anteil der Genres") +
  theme_light(20)
```

#

```{r}
count_genre_vs_year <- data_genre %>%
  select(Genre, year) %>% 
  group_by(year) %>% 
  distinct() %>% 
  count(year)
count_genre_vs_year %>%
  ggplot(aes(x = year, y = n)) +
  geom_point() +
  labs(title = "Anzahl der Genres nach Veröffentlichungsjahr",
       x = "Veröffentlichungsjahr",
       y = "Anzahl der Genres") +
  theme_light(20)
```

#

```{r}
count_genre_vs_year %>%
  ggplot(aes(x = year, y = n)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Anzahl der Genres nach Veröffentlichungsjahr",
       x = "Veröffentlichungsjahr",
       y = "Anzahl der Genres") +
  theme_light(20)
```
